name: CI/CD for Nokia-Swipes API

on:
  push:
    branches:
      - main
      - server_1.0
  pull_request:
    branches:
      - main
      - server_1.0

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Newman (Postman CLI)
      run: npm install -g newman

    - name: Run Postman Collection
      run: |
        newman run ./server/test/Nokia-Swipes.postman_collection.json \
          --env-var "NODE_ENV=development" \
          --env-var "PORT=3000" \
          --env-var "DB_URL=${{ secrets.DB_URL }}" \
          --env-var "OPENAI_API_URL=${{ secrets.OPENAI_API_URL }}" \
          --env-var "MONGODB_URI=null" \
          --disable-unicode \
          --reporters cli,json \
          --reporter-json-export newman-results.json

    - name: Archive Test Results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: newman-results
        path: newman-results.json