name: CI/CD for Nokia-Swipes API

on:
  push:
    branches:
      - main
      - server_1.0
  pull_request:
    branches:
      - main
      - server_1.0

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Newman (Postman CLI)
      run: npm install -g newman

    - name: Run Postman Collection
      run: |
        newman run ./server/test/Nokia-Swipes.postman_collection.json \
          --env-var "DB_CONNECTION_STRING=null" \
          --env-var "MONGODB_URI=null" \
          --disable-unicode \
          --reporters cli,json \
          --reporter-json-export newman-results.json

    - name: Archive Test Results
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: newman-results
        path: newman-results.json